using UnityEditor;
using UnityEngine;

namespace Coffee.UISoftMask
{
    public class AutoGeneratedEditor : Editor
    {
        private static readonly GUIContent s_Help = new GUIContent(
            "This component is automatically generated and will be not saved in the scene or prefab.");

        public override void OnInspectorGUI()
        {
            EditorGUILayout.HelpBox(s_Help);
        }
    }

    [CustomEditor(typeof(TerminalMaskingShape))]
    [CanEditMultipleObjects]
    public class TerminalMaskingShapeEditor : AutoGeneratedEditor
    {
    }

    [CustomEditor(typeof(MaskingShapeContainer))]
    [CanEditMultipleObjects]
    public class MaskingShapeContainerEditor : AutoGeneratedEditor
    {
    }
}
